In [1]:
import numpy as np
import time

# Data Structure

## Rank 1 Array
It is neighter a column or row vector

In [20]:
a=np.random.rand(10000)
print('a is ',a,'\n')
print('Shape of a is',a.shape,'\n')
print('a is a rank 1 array, we dont use this in deep learning coding.')

a is  [ 0.7596722   0.62479242  0.6133298  ...,  0.89592354  0.12794423
  0.53782594] 

Shape of a is (10000,) 

a is a rank 1 array, we dont use this in deep learning coding.


In [23]:
a.T 
# a transpose is same as a.

array([ 0.7596722 ,  0.62479242,  0.6133298 , ...,  0.89592354,
        0.12794423,  0.53782594])

## Numpy array

In [28]:
a=np.random.randn(5,1)
print('a is ',a,'\n')
print('Shape of a is',a.shape,'\n')
print('a is a 5x1 column vector.')

a is  [[-0.19473661]
 [ 0.79441682]
 [-1.25127324]
 [-0.0313365 ]
 [-1.25358584]] 

Shape of a is (5, 1) 

a is a 5x1 column vector.


## ndarray

In [2]:
import numpy as np
import time

In [27]:
sample_data=np.random.randint(low=0, high=10,size=(2,3,4,5))
sample_data
# (2，3，4，5)就是按照次序相互嵌套，最里层的是5个element.

array([[[[2, 3, 0, 3, 2],
         [0, 4, 8, 2, 5],
         [3, 5, 2, 0, 5],
         [1, 3, 9, 2, 9]],

        [[6, 3, 4, 5, 8],
         [9, 5, 7, 8, 6],
         [2, 3, 2, 5, 4],
         [8, 3, 6, 1, 6]],

        [[2, 4, 5, 2, 7],
         [0, 6, 0, 4, 7],
         [7, 2, 3, 3, 6],
         [2, 3, 8, 9, 7]]],


       [[[0, 3, 1, 1, 5],
         [2, 2, 8, 9, 8],
         [5, 0, 9, 7, 4],
         [5, 0, 4, 4, 2]],

        [[0, 2, 3, 7, 5],
         [4, 4, 9, 0, 3],
         [4, 8, 2, 7, 8],
         [1, 3, 8, 4, 6]],

        [[0, 7, 7, 9, 1],
         [8, 3, 1, 9, 6],
         [8, 9, 1, 0, 0],
         [5, 2, 3, 3, 0]]]])

## np.reshape
np.reshape( )=ndarray.reshape( )
<br>用上面ndarray的数据

In [33]:
sample_data.reshape(2,-1)

# -1 表示dimension根据情况自动计算. 

# reshape的排列顺序就是按照最里层的开始，按照次序一个一个对堆叠. Nothing sepecial.

array([[2, 3, 0, 3, 2, 0, 4, 8, 2, 5, 3, 5, 2, 0, 5, 1, 3, 9, 2, 9, 6, 3,
        4, 5, 8, 9, 5, 7, 8, 6, 2, 3, 2, 5, 4, 8, 3, 6, 1, 6, 2, 4, 5, 2,
        7, 0, 6, 0, 4, 7, 7, 2, 3, 3, 6, 2, 3, 8, 9, 7],
       [0, 3, 1, 1, 5, 2, 2, 8, 9, 8, 5, 0, 9, 7, 4, 5, 0, 4, 4, 2, 0, 2,
        3, 7, 5, 4, 4, 9, 0, 3, 4, 8, 2, 7, 8, 1, 3, 8, 4, 6, 0, 7, 7, 9,
        1, 8, 3, 1, 9, 6, 8, 9, 1, 0, 0, 5, 2, 3, 3, 0]])

# Summation

In [6]:
a=np.array([[0, 0, 0],
       [0, 1, 0],
       [0, 2, 0],
       [1, 0, 0],
       [1, 1, 0]])
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 2, 0],
       [1, 0, 0],
       [1, 1, 0]])

In [7]:
np.sum(a)

6

In [9]:
np.sum(a,axis=1)

array([0, 1, 2, 1, 2])

In [10]:
np.sum(a, keepdims=True,axis=1)

array([[0],
       [1],
       [2],
       [1],
       [2]])

In [14]:
np.sum(a,axis=0)

array([2, 4, 0])

In [17]:
np.sum(a, keepdims=True,axis=0)

array([[2, 4, 0]])

In [15]:
np.shape(np.sum(a, keepdims=True,axis=0))

(1, 3)

# Production

## np.dot
若是数据是array形式，then this is normal matrix multiplication.

In [35]:
import numpy as np

In [53]:
a = np.random.randint(0,10,(1,2))
print('a: ',a)
b = np.random.randint(0,10,(1,2))
print('b: ',b)

a:  [[4 7]]
b:  [[1 9]]


In [54]:
dot_prod = np.dot(a.T,b)
print(dot_prod)

[[ 4 36]
 [ 7 63]]


**若数据是list形式，则不用转置.**

In [62]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("\ndot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms\n")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("\nouter = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms\n")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("\nelementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms\n")


dot = 278
 ----- Computation time = 0.09199999999998099ms


outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.11899999999975819ms


elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.16700000000025028ms



# Vectorization

## Product of vectors

In [2]:
a=np.random.rand(10000)
b= np.random.rand(10000)
print('a:\n',a)
print('\nType of a is',type(a))
print('\nb:\n',b)

a:
 [ 0.77995441  0.12196738  0.87082693 ...,  0.00808     0.70840525
  0.41778966]

Type of a is <class 'numpy.ndarray'>

b:
 [ 0.96921684  0.97355159  0.95395174 ...,  0.10123722  0.83658746
  0.19243381]


In [3]:
tic = time.time()
c = np.dot(a,b)
toc= time.time()
print('Vectorization product takes '+str(1000*(toc-tic))+' ms')

Vectorization product takes 5.850791931152344 ms


# Broadcast

In [36]:
b= np.array([[2,3,4,5],[9,4,2,5]])
b

array([[2, 3, 4, 5],
       [9, 4, 2, 5]])

In [42]:
c=b+100
print('c is:\n',c)


c is:
 [[102 103 104 105]
 [109 104 102 105]]
