In [1]:
import tensorflow as tf
import numpy as np

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Multiplication

In [2]:
# Basic Operations with variable as graph input
# The value returned by the constructor represents the output
# of the Variable op. (define as input when running session)
# tf Graph input
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)

In [3]:
# Define some operations
add = tf.add(a, b)
mul = tf.multiply(a, b)

In [4]:
# Launch the default graph.
with tf.Session() as sess:
    # Run every operation with variable input
    print ("Addition with variables: %i" % sess.run(add, feed_dict={a: 2, b: 3}))
    print ("Multiplication with variables: %i" % sess.run(mul, feed_dict={a: 2, b: 3}))

Addition with variables: 5
Multiplication with variables: 6


# Transpose, reshape, split

In [5]:
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

In [6]:
sess = tf.InteractiveSession()
norm = tf.random_normal([2, 3, 4], mean=-1, stddev=4, seed=2)
B=tf.transpose(norm, [0,1,2])
#如果这两个不一起run的话，取值会不一样
a,b = sess.run((norm, B))
print('norm:\n',a)
print('\ntranspose:\n',b)

norm:
 [[[-4.4324436  -1.7864919  -0.4441982  -5.885107  ]
  [-2.6136513  -5.5816164   1.5592961  -7.3064475 ]
  [-5.1040425   1.5140333  -4.312895    0.38670862]]

 [[ 4.5946374   3.2871914   3.8917308  -1.2915606 ]
  [ 0.66414404  1.3910279   1.5351808   0.6709045 ]
  [ 2.3049917  -5.645281    2.3798478  -4.5707197 ]]]

transpose:
 [[[-4.4324436  -1.7864919  -0.4441982  -5.885107  ]
  [-2.6136513  -5.5816164   1.5592961  -7.3064475 ]
  [-5.1040425   1.5140333  -4.312895    0.38670862]]

 [[ 4.5946374   3.2871914   3.8917308  -1.2915606 ]
  [ 0.66414404  1.3910279   1.5351808   0.6709045 ]
  [ 2.3049917  -5.645281    2.3798478  -4.5707197 ]]]


In [7]:
X = tf.random_normal([2, 3, 4], mean=-1, stddev=4, seed=2)
XT = tf.transpose(X, perm=[0,2,1])
X_split = tf.split(XT, 2, axis=0)

#如果这两个不一起run的话，取值会不一样
a,b,c = sess.run((X, XT, X_split))
print('X_norm:\n',a)
print('\nX_transpose:\n',b)
print('\nshape of b:\n', np.shape(b))
print('\nX_split:\n', c)

X_norm:
 [[[-4.4324436  -1.7864919  -0.4441982  -5.885107  ]
  [-2.6136513  -5.5816164   1.5592961  -7.3064475 ]
  [-5.1040425   1.5140333  -4.312895    0.38670862]]

 [[ 4.5946374   3.2871914   3.8917308  -1.2915606 ]
  [ 0.66414404  1.3910279   1.5351808   0.6709045 ]
  [ 2.3049917  -5.645281    2.3798478  -4.5707197 ]]]

X_transpose:
 [[[-4.4324436  -2.6136513  -5.1040425 ]
  [-1.7864919  -5.5816164   1.5140333 ]
  [-0.4441982   1.5592961  -4.312895  ]
  [-5.885107   -7.3064475   0.38670862]]

 [[ 4.5946374   0.66414404  2.3049917 ]
  [ 3.2871914   1.3910279  -5.645281  ]
  [ 3.8917308   1.5351808   2.3798478 ]
  [-1.2915606   0.6709045  -4.5707197 ]]]

shape of b:
 (2, 4, 3)

X_split:
 [array([[[-4.4324436 , -2.6136513 , -5.1040425 ],
        [-1.7864919 , -5.5816164 ,  1.5140333 ],
        [-0.4441982 ,  1.5592961 , -4.312895  ],
        [-5.885107  , -7.3064475 ,  0.38670862]]], dtype=float32), array([[[ 4.5946374 ,  0.66414404,  2.3049917 ],
        [ 3.2871914 ,  1.3910279 , -5

In [8]:
b

array([[[-4.4324436 , -2.6136513 , -5.1040425 ],
        [-1.7864919 , -5.5816164 ,  1.5140333 ],
        [-0.4441982 ,  1.5592961 , -4.312895  ],
        [-5.885107  , -7.3064475 ,  0.38670862]],

       [[ 4.5946374 ,  0.66414404,  2.3049917 ],
        [ 3.2871914 ,  1.3910279 , -5.645281  ],
        [ 3.8917308 ,  1.5351808 ,  2.3798478 ],
        [-1.2915606 ,  0.6709045 , -4.5707197 ]]], dtype=float32)

In [9]:
c[0]

array([[[-4.4324436 , -2.6136513 , -5.1040425 ],
        [-1.7864919 , -5.5816164 ,  1.5140333 ],
        [-0.4441982 ,  1.5592961 , -4.312895  ],
        [-5.885107  , -7.3064475 ,  0.38670862]]], dtype=float32)

# Tensor Indexing

## tf.slice
- input: Tensor
- begin: starting location for each dimension of input
- size: number of elements for each dimension of input, **using -1 includes all remaining elements**

In [190]:
# sess=tf.InteractiveSession()
A=tf.constant([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]]])
'''
tf.slice:
-----------
input: Tensor
begin: starting location for each dimension of input
size: number of elements for each dimension of input, using -1 includes all remaining elements
'''
B=tf.slice(A, begin=[0,0,0], size=[2, 2, 2])
print('A:\n',sess.run(A))
print('\nB:\n',sess.run(B))

A:
 [[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]

B:
 [[[1 1]
  [2 2]]

 [[4 4]
  [5 5]]]


In [178]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])
tmp1=tf.slice(t, [1, 0, 0], [1, 1, 3])  # [[[3, 3, 3]]]
tmp2=tf.slice(t, [1, 0, 0], [1, 2, 3])  # [[[3, 3, 3], [4, 4, 4]]]
tmp3=tf.slice(t, [1, 0, 0], [2, 1, 3]) 

In [179]:
sess.run(tmp1)

array([[[3, 3, 3]]], dtype=int32)

In [180]:
sess.run(tmp2)

array([[[3, 3, 3],
        [4, 4, 4]]], dtype=int32)

In [181]:
sess.run(tmp3)

array([[[3, 3, 3]],

       [[5, 5, 5]]], dtype=int32)

# tf.gather & tf.gather_nd
- https://www.tensorflow.org/api_docs/python/tf/gather_nd
- https://www.tensorflow.org/api_docs/python/tf/gather


# tf.concat

In [46]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
t3=[t1, t2]

In [48]:
np.shape(t3)

(2, 2, 3)

In [52]:
np.array(t3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
sess.run(tf.concat(t3, axis=0))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [44]:
sess = tf.InteractiveSession()
norm = tf.random_normal([2, 3, 4], mean=-1, stddev=4, seed=2)
sess.run(tf.concat(norm, axis=0))

/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[[-4.4324436 , -1.7864919 , -0.4441982 , -5.885107  ],
        [-2.6136513 , -5.5816164 ,  1.5592961 , -7.3064475 ],
        [-5.1040425 ,  1.5140333 , -4.312895  ,  0.38670862]],

       [[ 4.5946374 ,  3.2871914 ,  3.8917308 , -1.2915606 ],
        [ 0.66414404,  1.3910279 ,  1.5351808 ,  0.6709045 ],
        [ 2.3049917 , -5.645281  ,  2.3798478 , -4.5707197 ]]],
      dtype=float32)

In [34]:
sess.run(norm)

array([[[ 1.8800287 , -2.551282  , -2.8095226 ,  2.8253038 ],
        [-3.3386943 ,  4.448929  , -3.208882  ,  0.83451724],
        [-7.983199  , -3.5477114 ,  1.3000367 , -0.14389127]],

       [[-1.6816882 , -4.810048  , -4.3068886 , -1.4531379 ],
        [ 3.9501557 , -5.481842  , -4.223766  , -6.3029575 ],
        [-2.6366472 , -5.7130976 , -4.6283875 , -2.1138787 ]]],
      dtype=float32)

# tf.where
相当于**conditional if-statement**

In [35]:
import tensorflow as tf
# import os
# os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

# Constants (3-element arrays).
a = tf.constant([100, 200, 300])
b = tf.constant([1, 2, 3])

# Use placeholder for predicate to where.
# ... We pass in an array of 3 bools to fill the placeholder.
j = tf.placeholder(tf.bool, shape=(3,)) # 下面的那个array_temp是个list,所以用(3,), 不过用[3]也是对的...
# j = tf.placeholder(tf.bool)

# Use where to apply 1 of 2 methods based on each predicate.
# ... First argument is the predicate (contains bools).
#     Second argument is run when true.
#     Third argument is run when false.
x = tf.where(j, a + 5000, a + b)

# Run with 3 bools in placeholder.
array_temp = [False, True, False]
result = tf.Session().run(x, {j: array_temp}) # use with to manage session is better

# For false, add 2 elements toe get her.
# ... For true, add 5000 to first element.
print(result)

[ 101 5200  303]


# Cross-Entropy Loss

## tf.nn.sigmoid_cross_entropy_with_logits

In [2]:
import tensorflow as tf

In [17]:
sess=tf.InteractiveSession()
# define diagonal matrix as labels.
y=tf.diag([1,1,1,1])
y=tf.cast(y, tf.float32)
y.eval()

/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [56]:
# define logits
z=tf.random_normal([4,4], seed=22)
z.eval()

array([[-1.1020602 ,  1.135856  , -0.07225064,  0.35086146],
       [ 1.3675061 , -1.761079  ,  1.0870513 , -0.15497802],
       [-1.6026533 , -0.00202283,  1.354184  ,  0.67207783],
       [ 0.5506696 ,  0.20571461, -0.78620875,  0.41342178]],
      dtype=float32)

In [87]:
sigmoid_cross_entropy=tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=z)
sigmoid_cross_entropy.eval()

array([[0.28096822, 0.8032713 , 0.39847443, 2.1555412 ],
       [0.672662  , 0.11806957, 0.6541165 , 0.9175534 ],
       [1.2964976 , 0.57337654, 0.5237489 , 0.5544817 ],
       [2.4085007 , 0.50966126, 0.7252496 , 0.27319372]], dtype=float32)

In [96]:
loss=tf.reduce_sum(sigmoid_cross_entropy, axis=1)
loss.eval()

array([3.4424815, 1.5473588, 3.3699217, 4.698089 ], dtype=float32)

In [102]:
# in case of not familiar with reduce_sum( , axis=...)
test=tf.random_normal([4,3])
print(test.eval())
tf.reduce_sum(test, axis=1).eval()

[[-0.60500604  0.09188548  0.00325186]
 [ 0.26136604 -0.11349762 -0.23580375]
 [ 1.0784042   0.65485626 -0.73389983]
 [ 0.8080843   1.1454443   0.9186316 ]]


array([-3.1609292 , -1.1041467 , -2.821066  ,  0.16600364], dtype=float32)

In [78]:
sess.close()

## tf.nn.softmax_cross_entropy_with_logits_v2

反向传播会同时对 logits 和 labels 起作用， 要禁止反向传播对 labels 起作用，将 labels 传递给 tf.stop_gradients 即可.

解释：https://lufficc.com/blog/tensorflow-notes
- 在监督学习中，labels 可以视为常量，不参与方向传播，只需要调整权重来拟合 labels。但有些情况（如对抗神经网络）labels 可能来自不同的地方.
- https://stats.stackexchange.com/questions/327348/how-is-softmax-cross-entropy-with-logits-different-from-softmax-cross-entropy-wi

In [15]:
'''
label是placeholder的时候就不用stop_gradient，因为label不是variable. 
下面主要是针对GAN的。就算是RNN，我们的label也是placeholder输入的.
'''

tf.nn.softmax_cross_entropy_with_logits_v2(
                    labels=tf.stop_gradient(labels),
                    logits=logits
                )

**下面是正常例子:**

In [1]:
import tensorflow as tf

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [15]:
'''这里的label是标准定义的prob dist.'''
# 这边不知为何list也能跑，不过tensorflow内部流动都是tensor，正式做肯定还会是要转成tensor的
labels = [[0.2,0.3,0.5],
          [0.1,0.6,0.3]]
logits = [[2,0.5,1],
          [0.1,1,3]]
logits_scaled = tf.nn.softmax(logits)

result1 = tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels, logits=logits) # True
result2 = -tf.reduce_sum(labels*tf.log(logits_scaled),1)
result3 = tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels, logits=logits_scaled) # wrong!

with tf.Session() as sess:
    print (sess.run(result1))
    print (sess.run(result2))
    print (sess.run(result3))
# >>>[ 1.41436887  1.66425455]
# >>>[ 1.41436887  1.66425455]
# >>>[ 1.17185783  1.17571414]

[1.4143689 1.6642545]
[1.4143689 1.6642545]
[1.1718578 1.1757141]


In [41]:
'''这里的label是onehot encoded的; 算是伪sprase_softmax_cross_entropy'''
labels = [[0, 0, 1],
          [0, 1, 0]]
logits = [[2,0.5,1],
          [0.1,1,3]]

cost = tf.nn.softmax_cross_entropy_with_logits_v2(labels=labels, logits=logits) # True

with tf.Session() as sess:
    print (sess.run(cost))

[1.4643688 2.1742544]


## tf.nn.sparse_softmax_cross_entropy_with_logits

In [35]:
# import tensorflow as tf

In [45]:
'''这里的label不能是onehot encoded的，会报错'''
# labels = tf.constant([[0, 0, 1],[0, 1, 0]])
# labels = tf.constant([2, 1])
# logits = tf.constant([[2, 0.5, 1], [0.1, 1, 3]])

labels = [2, 1]
logits = [[2, 0.5, 1], [0.1, 1, 3]]

cost = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=logits)
# result1 = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=logits) # True
# result2 = -tf.reduce_sum(labels*tf.log(logits_scaled),1)

with tf.Session() as sess:
    print (sess.run(cost))
#     print (sess.run(result2))


[1.4643688 2.1742544]


In [44]:
'''Onehot encoded，报错版'''
labels = tf.constant([[0, 0, 1],[0, 1, 0]])
logits = tf.constant([[2, 0.5, 1], [0.1, 1, 3]])


cost = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=logits)
# result1 = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=logits) # True
# result2 = -tf.reduce_sum(labels*tf.log(logits_scaled),1)

with tf.Session() as sess:
    print (sess.run(cost))
#     print (sess.run(result2))


ValueError: Rank mismatch: Rank of labels (received 2) should equal rank of logits minus 1 (received 2).

# Candidate Sampling

## tf.nn.fixed_unigram_candidate_sampler


In [2]:
import tensorflow as tf

labels_matrix = tf.reshape(tf.constant([1, 2, 3, 4], dtype=tf.int64), [-1, 1])

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [9]:
sampled_ids, true_expected_count, sampled_expected_count = tf.nn.fixed_unigram_candidate_sampler(
true_classes = labels_matrix,
num_true = 1,
num_sampled = 5,
unique = True,
range_max = 20,
distortion = 0.0,
unigrams = list(range(20))
)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    sampled_candidates, True_expected_count, Sampled_expected_count = sess.run([sampled_ids, 
                                                            true_expected_count, sampled_expected_count])
    print('sampled_candidates:',sampled_candidates)
    # True_expected_count: probability of each true samples got sampled
    print('True_expected_count:', True_expected_count)
    # Sampled_expected_count: probability of each sampled class occured
    print('Sampled_expected_count:',Sampled_expected_count)

sampled_candidates: [19  4 11  2 10]
True_expected_count: [[0.25]
 [0.25]
 [0.25]
 [0.25]]
Sampled_expected_count: [0.25 0.25 0.25 0.25 0.25]


# For Evaluation
## tf.nn.top.k

In [48]:
list(reversed(range(20)))

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [47]:
import tensorflow as tf

Input=tf.constant(list(reversed(range(20))))
top_k, top_idx=tf.nn.top_k(Input, k=3, sorted=True, name='top_k')
with tf.Session() as sess:
    print('top_k value:',sess.run(top_k))
    print('top_k index:',sess.run(top_idx))
    

top_k value: [19 18 17]
top_k index: [0 1 2]
