In [1]:
import tensorflow as tf
import numpy as np

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Multiplication

In [2]:
# Basic Operations with variable as graph input
# The value returned by the constructor represents the output
# of the Variable op. (define as input when running session)
# tf Graph input
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)

In [3]:
# Define some operations
add = tf.add(a, b)
mul = tf.multiply(a, b)

In [4]:
# Launch the default graph.
with tf.Session() as sess:
    # Run every operation with variable input
    print ("Addition with variables: %i" % sess.run(add, feed_dict={a: 2, b: 3}))
    print ("Multiplication with variables: %i" % sess.run(mul, feed_dict={a: 2, b: 3}))

Addition with variables: 5
Multiplication with variables: 6


# Transpose, reshape, split

In [5]:
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

In [6]:
sess = tf.InteractiveSession()
norm = tf.random_normal([2, 3, 4], mean=-1, stddev=4, seed=2)
B=tf.transpose(norm, [0,1,2])
#如果这两个不一起run的话，取值会不一样
a,b = sess.run((norm, B))
print('norm:\n',a)
print('\ntranspose:\n',b)

norm:
 [[[-4.4324436  -1.7864919  -0.4441982  -5.885107  ]
  [-2.6136513  -5.5816164   1.5592961  -7.3064475 ]
  [-5.1040425   1.5140333  -4.312895    0.38670862]]

 [[ 4.5946374   3.2871914   3.8917308  -1.2915606 ]
  [ 0.66414404  1.3910279   1.5351808   0.6709045 ]
  [ 2.3049917  -5.645281    2.3798478  -4.5707197 ]]]

transpose:
 [[[-4.4324436  -1.7864919  -0.4441982  -5.885107  ]
  [-2.6136513  -5.5816164   1.5592961  -7.3064475 ]
  [-5.1040425   1.5140333  -4.312895    0.38670862]]

 [[ 4.5946374   3.2871914   3.8917308  -1.2915606 ]
  [ 0.66414404  1.3910279   1.5351808   0.6709045 ]
  [ 2.3049917  -5.645281    2.3798478  -4.5707197 ]]]


In [7]:
X = tf.random_normal([2, 3, 4], mean=-1, stddev=4, seed=2)
XT = tf.transpose(X, perm=[0,2,1])
X_split = tf.split(XT, 2, axis=0)

#如果这两个不一起run的话，取值会不一样
a,b,c = sess.run((X, XT, X_split))
print('X_norm:\n',a)
print('\nX_transpose:\n',b)
print('\nshape of b:\n', np.shape(b))
print('\nX_split:\n', c)

X_norm:
 [[[-4.4324436  -1.7864919  -0.4441982  -5.885107  ]
  [-2.6136513  -5.5816164   1.5592961  -7.3064475 ]
  [-5.1040425   1.5140333  -4.312895    0.38670862]]

 [[ 4.5946374   3.2871914   3.8917308  -1.2915606 ]
  [ 0.66414404  1.3910279   1.5351808   0.6709045 ]
  [ 2.3049917  -5.645281    2.3798478  -4.5707197 ]]]

X_transpose:
 [[[-4.4324436  -2.6136513  -5.1040425 ]
  [-1.7864919  -5.5816164   1.5140333 ]
  [-0.4441982   1.5592961  -4.312895  ]
  [-5.885107   -7.3064475   0.38670862]]

 [[ 4.5946374   0.66414404  2.3049917 ]
  [ 3.2871914   1.3910279  -5.645281  ]
  [ 3.8917308   1.5351808   2.3798478 ]
  [-1.2915606   0.6709045  -4.5707197 ]]]

shape of b:
 (2, 4, 3)

X_split:
 [array([[[-4.4324436 , -2.6136513 , -5.1040425 ],
        [-1.7864919 , -5.5816164 ,  1.5140333 ],
        [-0.4441982 ,  1.5592961 , -4.312895  ],
        [-5.885107  , -7.3064475 ,  0.38670862]]], dtype=float32), array([[[ 4.5946374 ,  0.66414404,  2.3049917 ],
        [ 3.2871914 ,  1.3910279 , -5

In [8]:
b

array([[[-4.4324436 , -2.6136513 , -5.1040425 ],
        [-1.7864919 , -5.5816164 ,  1.5140333 ],
        [-0.4441982 ,  1.5592961 , -4.312895  ],
        [-5.885107  , -7.3064475 ,  0.38670862]],

       [[ 4.5946374 ,  0.66414404,  2.3049917 ],
        [ 3.2871914 ,  1.3910279 , -5.645281  ],
        [ 3.8917308 ,  1.5351808 ,  2.3798478 ],
        [-1.2915606 ,  0.6709045 , -4.5707197 ]]], dtype=float32)

In [9]:
c[0]

array([[[-4.4324436 , -2.6136513 , -5.1040425 ],
        [-1.7864919 , -5.5816164 ,  1.5140333 ],
        [-0.4441982 ,  1.5592961 , -4.312895  ],
        [-5.885107  , -7.3064475 ,  0.38670862]]], dtype=float32)

# Tensor Indexing

## tf.slice
- input: Tensor
- begin: starting location for each dimension of input
- size: number of elements for each dimension of input, **using -1 includes all remaining elements**

In [190]:
# sess=tf.InteractiveSession()
A=tf.constant([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]]])
'''
tf.slice:
-----------
input: Tensor
begin: starting location for each dimension of input
size: number of elements for each dimension of input, using -1 includes all remaining elements
'''
B=tf.slice(A, begin=[0,0,0], size=[2, 2, 2])
print('A:\n',sess.run(A))
print('\nB:\n',sess.run(B))

A:
 [[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]

B:
 [[[1 1]
  [2 2]]

 [[4 4]
  [5 5]]]


In [178]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])
tmp1=tf.slice(t, [1, 0, 0], [1, 1, 3])  # [[[3, 3, 3]]]
tmp2=tf.slice(t, [1, 0, 0], [1, 2, 3])  # [[[3, 3, 3], [4, 4, 4]]]
tmp3=tf.slice(t, [1, 0, 0], [2, 1, 3]) 

In [179]:
sess.run(tmp1)

array([[[3, 3, 3]]], dtype=int32)

In [180]:
sess.run(tmp2)

array([[[3, 3, 3],
        [4, 4, 4]]], dtype=int32)

In [181]:
sess.run(tmp3)

array([[[3, 3, 3]],

       [[5, 5, 5]]], dtype=int32)

# tf.gather & tf.gather_nd
- https://www.tensorflow.org/api_docs/python/tf/gather_nd
- https://www.tensorflow.org/api_docs/python/tf/gather

In [46]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
t3=[t1, t2]

In [48]:
np.shape(t3)

(2, 2, 3)

In [52]:
np.array(t3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
sess.run(tf.concat(t3, axis=0))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [44]:
sess = tf.InteractiveSession()
norm = tf.random_normal([2, 3, 4], mean=-1, stddev=4, seed=2)
sess.run(tf.concat(norm, axis=0))

/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[[-4.4324436 , -1.7864919 , -0.4441982 , -5.885107  ],
        [-2.6136513 , -5.5816164 ,  1.5592961 , -7.3064475 ],
        [-5.1040425 ,  1.5140333 , -4.312895  ,  0.38670862]],

       [[ 4.5946374 ,  3.2871914 ,  3.8917308 , -1.2915606 ],
        [ 0.66414404,  1.3910279 ,  1.5351808 ,  0.6709045 ],
        [ 2.3049917 , -5.645281  ,  2.3798478 , -4.5707197 ]]],
      dtype=float32)

In [34]:
sess.run(norm)

array([[[ 1.8800287 , -2.551282  , -2.8095226 ,  2.8253038 ],
        [-3.3386943 ,  4.448929  , -3.208882  ,  0.83451724],
        [-7.983199  , -3.5477114 ,  1.3000367 , -0.14389127]],

       [[-1.6816882 , -4.810048  , -4.3068886 , -1.4531379 ],
        [ 3.9501557 , -5.481842  , -4.223766  , -6.3029575 ],
        [-2.6366472 , -5.7130976 , -4.6283875 , -2.1138787 ]]],
      dtype=float32)

In [20]:
a,b=sess.run(norm, tf.concat(norm, axis=1))

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.