In [1]:
import numpy as np
import tensorflow as tf

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## Lookup a value from a vector

In [2]:
sess=tf.InteractiveSession()

In [3]:
params = tf.constant([10,20,30,40])
ids = tf.constant([0,1,2,3])

print (tf.nn.embedding_lookup(params,ids).eval())

[10 20 30 40]


## Lookup from a matrix

In [4]:
params = tf.random_uniform(shape=[4,3],minval=0, maxval=50,dtype=tf.int32,seed=2)
ids = tf.constant([2])
lookup = tf.nn.embedding_lookup(params, ids)

Parameters, IDs, Lookup = sess.run([params, ids, lookup])
print('Parameter Matrix is:\n', Parameters)
print('\nIDs is: \n', ids)
print('\nEmbedding Lookup Result is:\n', Lookup)

Parameter Matrix is:
 [[41  6 46]
 [27 39 45]
 [47 27 24]
 [26 39 13]]

IDs is: 
 Tensor("Const_2:0", shape=(1,), dtype=int32)

Embedding Lookup Result is:
 [[47 27 24]]
