In [1]:
import tensorflow as tf
import numpy as np

/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Tensorflow

In [2]:
# Parameters
learning_rate = 0.1
num_steps = 500
batch_size = 128
display_step = 100

# Network Parameters
n_hidden_1 = 256 # 1st layer number of neurons
n_hidden_2 = 256 # 2nd layer number of neurons
num_input = 784 # MNIST data input (img shape: 28*28)
num_classes = 10 # MNIST total classes (0-9 digits)

# tf Graph input
X = tf.placeholder("float", [None, num_input])
Y = tf.placeholder("float", [None, num_classes])

In [3]:

# Store layers weight & bias# Store 
weights = {
    'h1': tf.Variable(tf.random_normal([num_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, num_classes]))
}
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([num_classes]))
}

In [6]:
tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)

[<tf.Variable 'Variable:0' shape=(784, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_1:0' shape=(256, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_2:0' shape=(256, 10) dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_4:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_5:0' shape=(10,) dtype=float32_ref>]

In [7]:
tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)

[<tf.Variable 'Variable:0' shape=(784, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_1:0' shape=(256, 256) dtype=float32_ref>,
 <tf.Variable 'Variable_2:0' shape=(256, 10) dtype=float32_ref>,
 <tf.Variable 'Variable_3:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_4:0' shape=(256,) dtype=float32_ref>,
 <tf.Variable 'Variable_5:0' shape=(10,) dtype=float32_ref>]

# TF Eager

In [2]:
tf.__version__

'1.8.0'

In [2]:
tf.executing_eagerly()

True

In [6]:
x = [[2]]
m=tf.matmul(x, x)
m

<tf.Tensor: id=5, shape=(1, 1), dtype=int32, numpy=array([[4]], dtype=int32)>

In [8]:
print(m)
print("hello, {}".format(m))  # => "hello, [[4.]]"

tf.Tensor([[4]], shape=(1, 1), dtype=int32)
hello, [[4]]


In [9]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [26]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    for num in range(max_num):
        num = tf.constant(num)
        print(num,'====================')
        if num % 3 == 0 and num % 5 == 0:
            print('FizzBuzz')
        elif num % 3 == 0:
            print('Fizz')
        elif num % 5 == 0:
            print('Buzz')
        else:
            print(num,'==============')
        counter += 1
    return counter

In [27]:
fizzbuzz(10)

tf.Tensor(0, shape=(), dtype=int32) ====================
tf.Tensor(0, shape=(), dtype=int32) ==============
tf.Tensor(1, shape=(), dtype=int32) ====================
tf.Tensor(1, shape=(), dtype=int32) ==============
tf.Tensor(2, shape=(), dtype=int32) ====================
tf.Tensor(2, shape=(), dtype=int32) ==============
tf.Tensor(3, shape=(), dtype=int32) ====================
tf.Tensor(3, shape=(), dtype=int32) ==============
tf.Tensor(4, shape=(), dtype=int32) ====================
tf.Tensor(4, shape=(), dtype=int32) ==============
tf.Tensor(5, shape=(), dtype=int32) ====================
tf.Tensor(5, shape=(), dtype=int32) ==============
tf.Tensor(6, shape=(), dtype=int32) ====================
tf.Tensor(6, shape=(), dtype=int32) ==============
tf.Tensor(7, shape=(), dtype=int32) ====================
tf.Tensor(7, shape=(), dtype=int32) ==============
tf.Tensor(8, shape=(), dtype=int32) ====================
tf.Tensor(8, shape=(), dtype=int32) ==============
tf.Tensor(9, shape=(), dtype

<tf.Tensor: id=437, shape=(), dtype=int32, numpy=10>

In [45]:
a=tf.constant(10)
a

<tf.Tensor: id=439, shape=(), dtype=int32, numpy=10>

In [46]:
print(a)

tf.Tensor(10, shape=(), dtype=int32)


In [48]:
a.numpy()

10

In [1]:
import tensorflow as tf
import numpy as np
# `_compute_sampled_logits` is invoked in nce_loss to generate negative sample and calculate logits
from tensorflow.python.ops.nn_impl import _compute_sampled_logits

embedding_size = 10
words_number = 300
batch_size = 3
num_sampled = 3

graph = tf.Graph()
with graph.as_default():
    # Input data.
    train_inputs = tf.placeholder(tf.int32, shape=[batch_size])
    train_labels = tf.placeholder(tf.int64, shape=[batch_size, 1])

    with tf.device('/cpu:0'):
        embeddings = tf.Variable(
                tf.random_uniform([words_number, embedding_size], -4., 4.))
        embed = tf.nn.embedding_lookup(embeddings, train_inputs)
        nce_weights = tf.Variable(
                tf.random_uniform([words_number, embedding_size], -4., 4.))
        nce_biases = tf.Variable(tf.zeros([words_number]))
        
    logits, labels = _compute_sampled_logits(
                       weights=nce_weights,
                       biases=nce_biases,
                       inputs=embed,
                       labels=train_labels,
                       num_true=1,
                       num_sampled=num_sampled,
                       num_classes=words_number,
                       remove_accidental_hits = False)
    init = tf.global_variables_initializer()


session = tf.InteractiveSession(graph=graph)
init.run(session=session)

batch_inputs = np.array([0,1,2], dtype=np.int32)
batch_labels = np.array([[3],[4],[5]], dtype=np.int32)

feed_dict = {train_inputs : batch_inputs, train_labels : batch_labels}
logits_val, labels_val = session.run([logits, labels], feed_dict=feed_dict)

print ("logits_val = {}".format(logits_val))
print ("labels_val = {}".format(labels_val))


/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


logits_val = [[-17.112705    8.424343   -9.98695     1.564148 ]
 [  5.7143393  25.274858    9.833427   38.524017 ]
 [ 27.242645    5.347592   20.710701    4.2898164]]
labels_val = [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
